### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by shuyi122425** [novoalab/m6ABasecaller#7]
Hello,

I believe that m6ABasecaller is a valuable tool for m6A detection at the single molecule level, which is highly essential for our work. I have a couple of questions regarding this tool. Firstly, I am interested in knowing the supported ONT sequencing versions. I have only come across information stating its support for R9 version data, but I couldn't find any mention of support for the R10 version. Secondly, during the m6A basecalling process, I am curious to know if the m6A DARCH motif is detected.

**Comment by Theo-Nelson** [comment]
I am not the developer - but these base-calling models are generally chemistry-specific - since the chemistry impacts the expected means and standard deviations of the pA signal for different 5mers sequences in the pore.

If you are looking for an m6a basecaller for R10, Dorado now has one integrated: https://github.com/nanoporetech/dorado

See (rna004_130bps_sup@v3.0.1)

**Comment by enovoa** [comment]
Hi, @shuyi122425 thanks for your comment and sorry for slow response. To answer your questions:
- We are planning to develop an upgraded version for RNA chemistry (in the case of RNA) and R10 chemistry (in the case of DNA). We are currently working on generating some datasets to train new models, but this is still ongoing work as there were some additional adjustments that were needed with the change of chemistry
- With regards to the m6A basecalling process, yes the m6A DRACH motif is detected, because the model that we have released was trained with human in vivo data. Notably, if the algorithm would be trained with other types of data, a different motif could be detected. And thus could be applied to other types of modifications (not just m6A). 

Yes, as @Theo-Nelson mentions for R10 there is currently Dorado with m6A detection option (thanks!). As far as I know, this model is was trained to only detect m6A in DRACH motif because the synthetic sequences contained DRACH. So the dorado model will capture the DRACH motif because it is is the only motif in which it can capture m6A, if that makes sense.  If this is what you want to do, then dorado can also be an option. In our hands, it produces a higher number of false positives than our m6ABasecaller model, but these results are not yet unpublished. 

Best,
Eva
